### ISSUE TITLE
Soft reset

### ISSUE THREAD

**Issue by Paullake85** [Sensirion/shtc3-stm-sample-project#3]
Hello,

Can you explain to me the purpose of the soft reset demostrated in this sample code?
When it is useful to send the soft reset command? 
Is it good to soft reset the sensor periodically every let's say five minutes?

thx

**Comment by MBjoern** [comment]
Hi Paullake85

The Soft Reset can be used to fix the communication with the SHTC3 sensor, if at some point, it wouldn't be responding anymore. Calling the Soft Reset on a regular basis is not required, nor advised. In this example, we only demonstrate the soft reset, it's not required at all.

Best regards
